---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: application
  template:
    metadata:
      labels:
        app: app
        version: v1
        type: application
    spec:
      containers:
        - name: app
          image: app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: NodePort
  selector:
    type: application
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: app-cip-svc
spec:
  type: ClusterIP
  selector:
    type: application
  ports:
    - targetPort: 8080
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb-svc
spec:
  type: LoadBalancer
  selector:
    type: application
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30009