apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service-deployment
spec:
  selector:
    matchLabels:
      app: nginx-selector
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: nginx-selector
    spec:
      containers:
        - name: container
          image: nginx
          ports:
            - name: http
              containerPort: 8080
