apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp-deployment
  labels:
    app: dockerapp
    type: back-end
spec:
  template:
    metadata:
      name: dockerapp-pod
      labels:
        app: dockerapp
        type: back-end
    spec:
      containers:
        - name: dockerapp
          image: spring-boot-docker
  replicas: 3
  selector:
    matchLabels:
      type: back-end