apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller-service
  name: controller-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: controller-service
