logging.level.org.springframework.web: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


githubUsername: Nihrom77
messages:
  exchange:
    name: distributor_exchange
    routingKey:  distributor.placeOrder.${githubUsername}.{orderId}
    notify-routingkey: retailer.${githubUsername}


