create table if not exists item(
    id bigint generated by default as identity(start with 100) not null primary key,
    item_name varchar(100) not null
);

create table if not exists order1(
    id varchar(32) not null primary key,
    address varchar(200) not null,
    recipient varchar(200) not null
);

create table if not exists order_info(
    id varchar(32) not null primary key,
    order_id varchar(32) not null,
    status varchar(50) not null,
    signature varchar(50),
    constraint unique_uk_3 unique(order_id),
    constraint foreign_fk3 foreign key(order_id) references order1(id)
);

create table if not exists order_info_link(
    order_id varchar(32) not null,
    item_id bigint not null,
    constraint unique_uk_4 unique(order_id, item_id),
    constraint foreign_fk4 foreign key(order_id) references order1(id),
    constraint foreign_fk5 foreign key(item_id) references item(id)
);